### ISSUE TITLE
Complexity

### ISSUE THREAD

**Issue by eineving** [Hagmar/dotfiles#1]
README.md does now have too many complex instrucitons, could you create a taskforce for this and get it done in an upcoming sprint?

**Comment by Hagesjo** [comment]
Instructions still unclear, my life is ruined. 
![screenshot from 2015-08-25 13 51 26](https://cloud.githubusercontent.com/assets/1355632/9465852/7f64e0d8-4b30-11e5-93b4-c6e06af2a0a8.png)

**Comment by Hagmar** [comment]
Ah right, I forgot to include the "RUN!" instruction! That is definitely a feature, though.

**Comment by Hagmar** [comment]
Fixed by ignoring until it fixed itself, as all hard issues do

**Comment by Hagesjo** [comment]
Doesn't work on my machine. Please reopen.
